title: Git Text
lang: ko
email: infohojin@naver.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://git.jiny.dev"  # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: infohojin
github_username:  infohojin

source: src
destination: docs

github_url: https://github.com/jinygit/text

sass:
  load_paths:
    - _sass
    - ../node_modules/bootstrap/scss

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap